export const AppStrings = {
  appName: 'Attendance',
  signIn: 'Sign In',
  username: 'Username',
  pinCode: 'Pin Code',
  usernameNotEmpty: 'Username cannot be empty',
  pinCodeNotEmpty: 'Pin code cannot be emnpty',
  pinCodePatternError: 'Pin code must be 4 digits',
  invalidCreds: 'Invalid credentials',
  changePassword: 'Change Password',
  confirm: 'Confirm',
  noUserLoggedIn: 'No user is looged in',
  somethingWentWrong: 'Something went wrong',
  openSettings: 'Open Settings',
  logout: 'Logout',
  welcomBackUser: (fname: string) => `Welcome Back, ${fname}!`,
  readyPunchAttendance: 'Are you ready to punch in your attendance?',
  punchAttendance: 'Punch in attendance',
  pastAttendance: 'Past attendance',
  search: 'Search',
  searchPlaceholder: 'Date, status, etc...',
  attribute: 'Attribute',
  date: 'Date',
  status: 'Status',
  none: 'None',
  present: 'Present',
  absent: 'Absent',
  leave: 'Leave',
  applyForLeave: 'Apply for leave',
  dashboard: 'Dashboard',
  users: 'Users',
  settings: 'Settings',
  officeHours: 'Office Hours',
  saveChanges: 'Save Changes',
  startTime: 'Start Time',
  finishTime: 'Finish Time',
  workingHours: 'Working Hours',
  startTimeEmpty: 'Start Time cannot be empty',
  startTimePatternError: 'Start Time should be in the format hh:mm AM/PM',
  finishTimeEmpty: 'Start Time cannot be empty',
  finishTimePatternError: 'Start Time should be in the format hh:mm AM/PM',
  invalidStartTime: 'Start Time cannot be greater than Finish Time',
  invalidFinishTime: 'Finish Time cannot be less than Start Time',
  workingHoursEmpty: 'Working Hours cannot be empty',
  invalidWorkingHours: 'Working Hours cannot be less than 4',
  inconsistenWorkingHours: 'Working Hours does not match start and finish time',
  officeHoursUpdated: 'Office hours have been updated!',
  todaysAvailability: 'Today’s Availability',
  overallStats: 'Overall Stats',
  manageUsers: 'Manage users',
  name: 'Name',
  totalHours: 'Total Hours',
  dailyAverageHours: 'Daily Average Hours',
  addUser: 'Add User',
  searchUserLabel: 'Name, email, etc...',
  position: 'Position',
  positionsPlaceholder: 'Frontend, ...',
  email: 'Email',
  view: 'View',
  edit: 'Edit',
  delete: 'Delete',
  deleteUserTitle: 'Delete User',
  nevermind: 'Nevermind',
  deleteUser: 'Delete User',
  deletedUser: 'Deleted user',
  undo: 'Undo',
  editUser: 'Edit User',
  save: 'Save',
  discardChanges: 'Discard Changes',
  firstName: 'First Name',
  lastName: 'Last Name',
  designation: 'Designation',
  firstNameEmpty: 'First Name cannot be empty',
  lastNameEmpty: 'Last Name cannot be empty',
  designationEmpty: 'Designation cannot be empty',
  emailEmpty: 'Email cannot be empty',
  emailInvalid: 'Enter valid email',
} as const;
