export const AppStrings = {
  AppName: 'Attendance',
  SignIn: 'Sign In',
  Username: 'Username',
  PinCode: 'Pin Code',
  UsernameNotEmpty: 'Username cannot be empty',
  PinCodeNotEmpty: 'Pin code cannot be emnpty',
  PinCodePatternError: 'Pin code must be 4 digits',
  InvalidCreds: 'Invalid credentials',
  ChangePassword: 'Change Password',
  Confirm: 'Confirm',
  NoUserLoggedIn: 'No user is looged in',
  SomethingWentWrong: 'Something went wrong',
  OpenSettings: 'Open Settings',
  Logout: 'Logout',
  WelcomBackUser: (fname: string) => `Welcome Back, ${fname}!`,
  ReadyPunchAttendance: 'Are you ready to punch in your attendance?',
  PunchAttendance: 'Punch in attendance',
  PastAttendance: 'Past attendance',
  Search: 'Search',
  SearchPlaceholder: 'Date, status, etc...',
  Attribute: 'Attribute',
  Date: 'Date',
  Status: 'Status',
  None: 'None',
  Present: 'Present',
  Absent: 'Absent',
  Leave: 'Leave',
  ApplyForLeave: 'Apply for leave',
  Dashboard: 'Dashboard',
  Users: 'Users',
  Settings: 'Settings',
  OfficeHours: 'Office Hours',
  SaveChanges: 'Save Changes',
  StartTime: 'Start Time',
  FinishTime: 'Finish Time',
  WorkingHourse: 'Working Hours',
  StartTimeEmpty: 'Start Time cannot be empty',
  StartTimePatternError: 'Start Time should be in the format hh:mm AM/PM',
  FinishTimeEmpty: 'Start Time cannot be empty',
  FinishTimePatternError: 'Start Time should be in the format hh:mm AM/PM',
  InvalidStartTime: 'Start Time cannot be greater than Finish Time',
  InvalidFinishTime: 'Finish Time cannot be less than Start Time',
  WorkingHoursEmpty: 'Working Hours cannot be empty',
  InvalidWorkingHours: 'Working Hours cannot be less than 4',
  InconsistenWorkingHours: 'Working Hours does not match start and finish time',
  OfficeHoursUpdated: 'Office hours have been updated!',
  TodaysAvailability: 'Today’s Availability',
} as const;
