export const AppStrings = {
  AppName: 'Attendance',
  SignIn: 'Sign In',
  Username: 'Username',
  PinCode: 'Pin Code',
  UsernameNotEmpty: 'Username cannot be empty',
  PinCodeNotEmpty: 'Pin code cannot be emnpty',
  PinCodePatternError: 'Pin code must be 4 digits',
  InvalidCreds: 'Invalid credentials',
  ChangePassword: 'Change Password',
  Confirm: 'Confirm',
  NoUserLoggedIn: 'No user is looged in',
  SomethingWentWrong: 'Something went wrong',
  OpenSettings: 'Open Settings',
  Logout: 'Logout',
  WelcomBackUser: (fname: string) => `Welcome Back, ${fname}!`,
  ReadyPunchAttendance: 'Are you ready to punch in your attendance?',
  PunchAttendance: 'Punch in attendance',
  PastAttendance: 'Past attendance',
  Search: 'Search',
  SearchPlaceholder: 'Date, status, etc...',
  Attribute: 'Attribute',
  Date: 'Date',
  Status: 'Status',
  None: 'None',
  Present: 'Present',
  Absent: 'Absent',
  Leave: 'Leave',
  ApplyForLeave: 'Apply for leave',
} as const;
